basePath: /api
definitions:
  models.Bus:
    properties:
      assemblyDate:
        type: string
      brand:
        type: string
      busModel:
        type: string
      id:
        type: string
      lastRepairDate:
        type: string
      registerNumber:
        type: string
    type: object
  models.BusStop:
    properties:
      id:
        type: string
      lat:
        type: number
      long:
        type: number
      name:
        type: string
    type: object
  models.Driver:
    properties:
      birthDate:
        type: string
      id:
        type: string
      licenseSeries:
        type: string
      name:
        type: string
      passportSeries:
        type: string
      patronymic:
        type: string
      snils:
        type: string
      surname:
        type: string
    type: object
  models.Route:
    properties:
      id:
        type: string
      number:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact: {}
  description: API for bus manager backend
  title: Bus manager API
  version: "1.0"
paths:
  /buses/:
    get:
      description: Get bus list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Bus'
            type: array
        "404":
          description: Not Found
          schema:
            type: string
      summary: Get bus list
      tags:
      - buses
    post:
      description: Add bus
      parameters:
      - description: bus model
        in: body
        name: bus
        required: true
        schema:
          $ref: '#/definitions/models.Bus'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Bus'
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Add bus
      tags:
      - buses
  /buses/{id}:
    delete:
      description: Delete bus by ID
      parameters:
      - description: Bus ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Delete bus
      tags:
      - buses
    put:
      description: Update bus by ID
      parameters:
      - description: Bus ID
        in: path
        name: id
        required: true
        type: string
      - description: bus model
        in: body
        name: bus
        required: true
        schema:
          $ref: '#/definitions/models.Bus'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Bus'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Update bus
      tags:
      - buses
  /buses/id/{id}:
    get:
      description: Get bus by ID
      parameters:
      - description: Bus ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Bus'
        "404":
          description: Not Found
          schema:
            type: string
      summary: Get bus
      tags:
      - buses
  /buses/number/{number}:
    get:
      description: Get bus by number
      parameters:
      - description: Bus register number
        in: path
        name: number
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Bus'
        "404":
          description: Not Found
          schema:
            type: string
      summary: Get bus
      tags:
      - buses
  /drivers/:
    get:
      description: Get driver list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Driver'
            type: array
        "404":
          description: Not Found
          schema:
            type: string
      summary: Get driver list
      tags:
      - drivers
    post:
      description: Add driver
      parameters:
      - description: driver model
        in: body
        name: driver
        required: true
        schema:
          $ref: '#/definitions/models.Driver'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Driver'
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Add driver
      tags:
      - drivers
  /drivers/{id}:
    delete:
      description: Delete driver by ID
      parameters:
      - description: Driver ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Delete driver
      tags:
      - drivers
    put:
      description: Update driver by ID
      parameters:
      - description: Driver ID
        in: path
        name: id
        required: true
        type: string
      - description: driver model
        in: body
        name: driver
        required: true
        schema:
          $ref: '#/definitions/models.Driver'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Driver'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Update driver
      tags:
      - drivers
  /drivers/id/{id}:
    get:
      description: Get driver by ID
      parameters:
      - description: Driver ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Driver'
        "404":
          description: Not Found
          schema:
            type: string
      summary: Get driver
      tags:
      - drivers
  /drivers/series/{series}:
    get:
      description: Get driver by passport series
      parameters:
      - description: Driver passport series
        in: path
        name: series
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Driver'
        "404":
          description: Not Found
          schema:
            type: string
      summary: Get driver
      tags:
      - drivers
  /routes/:
    get:
      description: Get routes list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Route'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get routes list
      tags:
      - routes
    post:
      description: Add route
      parameters:
      - description: route model
        in: body
        name: route
        required: true
        schema:
          $ref: '#/definitions/models.Route'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Route'
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Add route
      tags:
      - routes
  /routes/{id}:
    delete:
      description: Delete route by ID
      parameters:
      - description: Route ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Delete route
      tags:
      - routes
    put:
      description: Update route by ID
      parameters:
      - description: Route ID
        in: path
        name: id
        required: true
        type: string
      - description: route model
        in: body
        name: route
        required: true
        schema:
          $ref: '#/definitions/models.Route'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Route'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Update route
      tags:
      - routes
  /routes/{id}/buses/:
    get:
      description: Get all buses on route by route ID
      parameters:
      - description: Route ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Bus'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get all buses on route
      tags:
      - routes
  /routes/{id}/buses/{busId}:
    delete:
      description: Unassign bus from route
      parameters:
      - description: Route ID
        in: path
        name: id
        required: true
        type: string
      - description: Bus ID
        in: path
        name: busId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Unassign bus from route
      tags:
      - routes
    post:
      description: Assign bus to route
      parameters:
      - description: Route ID
        in: path
        name: id
        required: true
        type: string
      - description: Bus ID
        in: path
        name: busId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Assign bus to route
      tags:
      - routes
  /routes/{id}/drivers/:
    get:
      description: Get all drivers on route by route ID
      parameters:
      - description: Route ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Driver'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get all drivers on route
      tags:
      - routes
  /routes/{id}/drivers/{driverId}:
    delete:
      description: Unassign driver from route
      parameters:
      - description: Route ID
        in: path
        name: id
        required: true
        type: string
      - description: Driver ID
        in: path
        name: driverId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Unassign driver from route
      tags:
      - routes
    post:
      description: Assign driver to route
      parameters:
      - description: Route ID
        in: path
        name: id
        required: true
        type: string
      - description: Driver ID
        in: path
        name: driverId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Assign driver to route
      tags:
      - routes
  /routes/{id}/stops/:
    get:
      description: Get all bus stops on route by route ID
      parameters:
      - description: Route ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.BusStop'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get all bus stops on route
      tags:
      - routes
  /routes/{id}/stops/{busStopId}:
    delete:
      description: Unassign bus stop from route
      parameters:
      - description: Route ID
        in: path
        name: id
        required: true
        type: string
      - description: Bus stop ID
        in: path
        name: busStopId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Unassign bus stop from route
      tags:
      - routes
    post:
      description: Assign bus stop to route
      parameters:
      - description: Route ID
        in: path
        name: id
        required: true
        type: string
      - description: Bus stop ID
        in: path
        name: busStopId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Assign bus stop to route
      tags:
      - routes
  /routes/id/{id}:
    get:
      description: Get route by number
      parameters:
      - description: Route number
        in: path
        name: number
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Route'
        "404":
          description: Not Found
          schema:
            type: string
      summary: Get route
      tags:
      - routes
  /stops/:
    get:
      description: Get bus stop list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.BusStop'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get bus stop list
      tags:
      - stops
    post:
      description: Add bus stop
      parameters:
      - description: bus stop model
        in: body
        name: bus
        required: true
        schema:
          $ref: '#/definitions/models.BusStop'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.BusStop'
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Add bus stop
      tags:
      - stops
  /stops/{id}:
    delete:
      description: Delete bus stop by ID
      parameters:
      - description: Bus stop ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Delete bus stop
      tags:
      - stops
    put:
      description: Update bus stop by ID
      parameters:
      - description: Bus stop ID
        in: path
        name: id
        required: true
        type: string
      - description: bus stop model
        in: body
        name: bus
        required: true
        schema:
          $ref: '#/definitions/models.BusStop'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.BusStop'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Update bus stop
      tags:
      - stops
  /stops/id/{id}:
    get:
      description: Get bus stop by ID
      parameters:
      - description: Bus stop ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.BusStop'
        "404":
          description: Not Found
          schema:
            type: string
      summary: Get bus stop
      tags:
      - stops
  /stops/name/{name}:
    get:
      description: Get bus stop by name
      parameters:
      - description: Bus stop name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.BusStop'
        "404":
          description: Not Found
          schema:
            type: string
      summary: Get bus stop
      tags:
      - stops
swagger: "2.0"
